myid:
  server:
    proxy:
      base-url: http://localhost:8080/myid-server/
      connection-timeout: 1000
      read-timeout: 1000
      httpclient:
        max-conn-total: 200
        max-conn-per-route: 200